### ISSUE TITLE
Reenable testing on PyPy on GitHub Actions once the PyYAML issue is resolved

### ISSUE THREAD

**Issue by smarr** [smarr/ReBench#225]
Currently, PyYAML can't be installed on PyPy on GitHub Actions.

See https://github.com/smarr/ReBench/actions/runs/5578565182/jobs/10192946324

Because of this, I am going to disable testing on it. But this should be reverted this is fixed.
Also, it worked earlier today, but the GHA versions don't seem to show any change...

```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/PyPy/3.10.12/x64/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/PyPy/3.10.12/x64/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/hostedtoolcache/PyPy/3.10.12/x64/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line [28](https://github.com/smarr/ReBench/actions/runs/5578565182/jobs/10192946324#step:7:29)8, in <module>
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/command/egg_info.py", line [31](https://github.com/smarr/ReBench/actions/runs/5578565182/jobs/10192946324#step:7:32)4, in run
          self.find_sources()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/command/egg_info.py", line [32](https://github.com/smarr/ReBench/actions/runs/5578565182/jobs/10192946324#step:7:33)2, in find_sources
          mm.run()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/command/sdist.py", line [33](https://github.com/smarr/ReBench/actions/runs/5578565182/jobs/10192946324#step:7:34)6, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-0h7xx5ej/overlay/lib/pypy3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Comment by smarr** [comment]
Was solved with #235.
