### ISSUE TITLE
signal.SIGKILL is only available on Unix-like systems

### ISSUE THREAD

**Issue by clin1234** [smarr/ReBench#241]
```
> rebench.exe
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Scripts\rebench.exe\__main__.py", line 4, in <module>
    from rebench.rebench import main_func
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\rebench\rebench.py", line 35, in <module>
    from .executor import Executor, BatchScheduler, RoundRobinScheduler, \
        RandomScheduler, BenchmarkThreadExceptions
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\rebench\executor.py", line 30, in <module>
    from . import subprocess_with_timeout as subprocess_timeout
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\rebench\subprocess_with_timeout.py", line 9, in <module>
    from .subprocess_kill import kill_process
  File "C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\site-packages\rebench\subprocess_kill.py", line 2, in <module>
    from signal     import SIGKILL
ImportError: cannot import name 'SIGKILL' from 'signal' (C:\Users\ךינשגכהד\scoop\apps\python-alpha\current\Lib\signal.py). Did you mean: 'SIGILL'?
```

**Comment by smarr** [comment]
Thanks for the interest in ReBench, unfortunately, I don't have the resources to support Windows. If you or others are interested in making it work on Windows, that's great, and I am happy to support it with guidance, code reviewing, and possibly even occasional attempts to keep a Windows CI setup green. Though, I won't be able to add Windows support myself.
